# Generated by Django 4.1.3 on 2022-11-22 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questEconomico',
            new_name='questSEconomico',
        ),
    ]
